# frozen_string_literal: true

module RubyLLM
  module Tribunal
    module Reporters
      # HTML report for shareable results.
      class HTML
        class << self
          def format(results)
            <<~HTML
              <!DOCTYPE html>
              <html lang="en">
              <head>
                <meta charset="UTF-8">
                <meta name="viewport" content="width=device-width, initial-scale=1.0">
                <title>Tribunal Evaluation Report</title>
                <style>
                  * { box-sizing: border-box; margin: 0; padding: 0; }
                  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; line-height: 1.6; padding: 2rem; background: #f5f5f5; }
                  .container { max-width: 900px; margin: 0 auto; }
                  h1 { color: #333; margin-bottom: 1.5rem; }
                  .summary { background: white; border-radius: 8px; padding: 1.5rem; margin-bottom: 1.5rem; box-shadow: 0 1px 3px rgba(0,0,0,0.1); }
                  .summary-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(150px, 1fr)); gap: 1rem; }
                  .stat { text-align: center; }
                  .stat-value { font-size: 2rem; font-weight: bold; color: #333; }
                  .stat-label { color: #666; font-size: 0.9rem; }
                  .status { padding: 0.5rem 1rem; border-radius: 4px; display: inline-block; font-weight: bold; margin-top: 1rem; }
                  .status.passed { background: #d4edda; color: #155724; }
                  .status.failed { background: #f8d7da; color: #721c24; }
                  .metrics { background: white; border-radius: 8px; padding: 1.5rem; margin-bottom: 1.5rem; box-shadow: 0 1px 3px rgba(0,0,0,0.1); }
                  .metrics h2 { margin-bottom: 1rem; color: #333; font-size: 1.2rem; }
                  .metric-row { display: flex; align-items: center; margin-bottom: 0.75rem; }
                  .metric-name { width: 120px; font-weight: 500; }
                  .metric-bar { flex: 1; height: 20px; background: #e9ecef; border-radius: 4px; overflow: hidden; margin: 0 1rem; }
                  .metric-fill { height: 100%; background: #28a745; transition: width 0.3s; }
                  .metric-fill.warning { background: #ffc107; }
                  .metric-fill.danger { background: #dc3545; }
                  .metric-value { width: 100px; text-align: right; font-size: 0.9rem; color: #666; }
                  .failures { background: white; border-radius: 8px; padding: 1.5rem; box-shadow: 0 1px 3px rgba(0,0,0,0.1); }
                  .failures h2 { margin-bottom: 1rem; color: #333; font-size: 1.2rem; }
                  .failure { background: #fff5f5; border-left: 4px solid #dc3545; padding: 1rem; margin-bottom: 1rem; border-radius: 0 4px 4px 0; }
                  .failure-input { font-weight: 500; color: #333; margin-bottom: 0.5rem; }
                  .failure-reason { color: #666; font-size: 0.9rem; }
                  .failure-reason code { background: #f1f1f1; padding: 0.2rem 0.4rem; border-radius: 3px; }
                  .footer { text-align: center; margin-top: 2rem; color: #666; font-size: 0.85rem; }
                </style>
              </head>
              <body>
                <div class="container">
                  <h1>Tribunal Evaluation Report</h1>
                  #{summary_section(results[:summary])}
                  #{metrics_section(results[:metrics])}
                  #{failures_section(results[:cases])}
                  <div class="footer">Generated by Tribunal</div>
                </div>
              </body>
              </html>
            HTML
          end

          private

          def summary_section(summary)
            passed = summary[:threshold_passed] != false && summary[:failed].zero?
            status_class = passed ? 'passed' : 'failed'
            status_text = passed ? 'PASSED' : 'FAILED'

            threshold_info = if summary[:strict]
                               ' (strict mode)'
                             elsif summary[:threshold]
                               " (threshold: #{(summary[:threshold] * 100).round}%)"
                             else
                               ''
                             end

            <<~HTML
              <div class="summary">
                <div class="summary-grid">
                  <div class="stat">
                    <div class="stat-value">#{summary[:total]}</div>
                    <div class="stat-label">Total Tests</div>
                  </div>
                  <div class="stat">
                    <div class="stat-value">#{summary[:passed]}</div>
                    <div class="stat-label">Passed</div>
                  </div>
                  <div class="stat">
                    <div class="stat-value">#{summary[:failed]}</div>
                    <div class="stat-label">Failed</div>
                  </div>
                  <div class="stat">
                    <div class="stat-value">#{(summary[:pass_rate] * 100).round}%</div>
                    <div class="stat-label">Pass Rate</div>
                  </div>
                  <div class="stat">
                    <div class="stat-value">#{format_duration(summary[:duration_ms])}</div>
                    <div class="stat-label">Duration</div>
                  </div>
                </div>
                <div class="status #{status_class}">#{status_text}#{threshold_info}</div>
              </div>
            HTML
          end

          def metrics_section(metrics)
            return '' if metrics.nil? || metrics.empty?

            rows = metrics.map { |name, data| format_metric_row(name, data) }.join("\n")

            <<~HTML
              <div class="metrics">
                <h2>Results by Metric</h2>
                #{rows}
              </div>
            HTML
          end

          def format_metric_row(name, data)
            rate = data[:total].positive? ? data[:passed].to_f / data[:total] : 0
            percent = (rate * 100).round

            fill_class = if percent >= 90
                           ''
                         elsif percent >= 70
                           'warning'
                         else
                           'danger'
                         end

            <<~HTML
              <div class="metric-row">
                <div class="metric-name">#{escape_html(name.to_s)}</div>
                <div class="metric-bar">
                  <div class="metric-fill #{fill_class}" style="width: #{percent}%"></div>
                </div>
                <div class="metric-value">#{data[:passed]}/#{data[:total]} (#{percent}%)</div>
              </div>
            HTML
          end

          def failures_section(cases)
            failures = cases.select { |c| c[:status] == :failed }
            return '' if failures.empty?

            rows = failures.map { |c| format_failure_row(c) }.join("\n")

            <<~HTML
              <div class="failures">
                <h2>Failed Cases</h2>
                #{rows}
              </div>
            HTML
          end

          def format_failure_row(test_case)
            reasons = test_case[:failures].map do |type, reason|
              "<code>#{escape_html(type.to_s)}</code>: #{escape_html(reason.to_s)}"
            end.join('<br>')

            <<~HTML
              <div class="failure">
                <div class="failure-input">#{escape_html(test_case[:input].to_s)}</div>
                <div class="failure-reason">#{reasons}</div>
              </div>
            HTML
          end

          def escape_html(str)
            str.to_s
               .gsub('&', '&amp;')
               .gsub('<', '&lt;')
               .gsub('>', '&gt;')
               .gsub('"', '&quot;')
          end

          def format_duration(duration_ms)
            return "#{duration_ms}ms" if duration_ms < 1000

            "#{(duration_ms / 1000.0).round(1)}s"
          end
        end
      end
    end
  end
end
